In [2]:
import torch.nn.functional as F
from torch.autograd import grad
import torch

y = torch.tensor([1.0])
x1 = torch.tensor([1.1])
w1 = torch.tensor([2.2], requires_grad=True)
b = torch.tensor([0.0], requires_grad=True)

z = x1 * w1 + b
a = torch.sigmoid(z)

loss = F.binary_cross_entropy(a, y)
grad_L_w1 = grad(loss, w1, retain_graph=True)
grad_L_b = grad(loss, b, retain_graph=True)

grad_L_w1, grad_L_b

((tensor([-0.0898]),), (tensor([-0.0817]),))

In [3]:
class NeuralNetwork(torch.nn.Module):
    def __init__(self, num_inputs, num_outputs):
        super().__init__()
        self.layers = torch.nn.Sequential(
            # 1st hidden layer
            torch.nn.Linear(num_inputs, 30),
            torch.nn.ReLU(),

            # 2nd hidden layer
            torch.nn.Linear(30, 20),
            torch.nn.ReLU(),

            # Output layer
            torch.nn.Linear(20, num_outputs)
        )

    def forward(self, x):
        logits = self.layers(x)
        return logits

model = NeuralNetwork(50, 3)
model

NeuralNetwork(
  (layers): Sequential(
    (0): Linear(in_features=50, out_features=30, bias=True)
    (1): ReLU()
    (2): Linear(in_features=30, out_features=20, bias=True)
    (3): ReLU()
    (4): Linear(in_features=20, out_features=3, bias=True)
  )
)

In [4]:
num_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
num_params

2213

In [5]:
for p in model.parameters():
    print(p)

Parameter containing:
tensor([[-7.7701e-02,  9.6179e-02,  8.2032e-02,  ..., -7.3616e-02,
          4.1474e-02, -2.3093e-02],
        [ 1.2712e-01, -8.4538e-02, -7.6582e-02,  ..., -5.2185e-02,
         -2.4461e-02,  8.1517e-02],
        [-4.9051e-02, -1.2317e-01, -1.7941e-02,  ...,  7.4182e-02,
          8.6651e-02, -4.5216e-02],
        ...,
        [-8.1992e-02, -7.3211e-03, -9.8215e-02,  ...,  5.8930e-02,
         -9.6521e-02, -3.9867e-02],
        [-7.9048e-02, -8.6462e-02,  3.9762e-02,  ..., -3.7804e-02,
          8.2959e-02,  9.7695e-03],
        [-8.6864e-02, -1.0334e-01,  6.3675e-05,  ..., -1.1742e-01,
          7.6699e-02, -1.6650e-02]], requires_grad=True)
Parameter containing:
tensor([-0.0693,  0.0261,  0.0271,  0.0625, -0.0791, -0.0056,  0.0976, -0.1115,
        -0.0084, -0.1224, -0.0935,  0.1000, -0.1182,  0.0301, -0.1065,  0.0484,
         0.0832, -0.0117, -0.1391,  0.0511, -0.0013, -0.0820,  0.1062, -0.0824,
         0.0459, -0.0689,  0.0882,  0.0397, -0.1168,  0.0386],
 

In [8]:
model.layers[0].weight, model.layers[0].weight.shape 

(Parameter containing:
 tensor([[-7.7701e-02,  9.6179e-02,  8.2032e-02,  ..., -7.3616e-02,
           4.1474e-02, -2.3093e-02],
         [ 1.2712e-01, -8.4538e-02, -7.6582e-02,  ..., -5.2185e-02,
          -2.4461e-02,  8.1517e-02],
         [-4.9051e-02, -1.2317e-01, -1.7941e-02,  ...,  7.4182e-02,
           8.6651e-02, -4.5216e-02],
         ...,
         [-8.1992e-02, -7.3211e-03, -9.8215e-02,  ...,  5.8930e-02,
          -9.6521e-02, -3.9867e-02],
         [-7.9048e-02, -8.6462e-02,  3.9762e-02,  ..., -3.7804e-02,
           8.2959e-02,  9.7695e-03],
         [-8.6864e-02, -1.0334e-01,  6.3675e-05,  ..., -1.1742e-01,
           7.6699e-02, -1.6650e-02]], requires_grad=True),
 torch.Size([30, 50]))

In [9]:
model.layers[0].bias, model.layers[0].bias.shape 

(Parameter containing:
 tensor([-0.0693,  0.0261,  0.0271,  0.0625, -0.0791, -0.0056,  0.0976, -0.1115,
         -0.0084, -0.1224, -0.0935,  0.1000, -0.1182,  0.0301, -0.1065,  0.0484,
          0.0832, -0.0117, -0.1391,  0.0511, -0.0013, -0.0820,  0.1062, -0.0824,
          0.0459, -0.0689,  0.0882,  0.0397, -0.1168,  0.0386],
        requires_grad=True),
 torch.Size([30]))

In [10]:
torch.manual_seed(123)
model = NeuralNetwork(50, 3)
model.layers[0].weight

Parameter containing:
tensor([[-0.0577,  0.0047, -0.0702,  ...,  0.0222,  0.1260,  0.0865],
        [ 0.0502,  0.0307,  0.0333,  ...,  0.0951,  0.1134, -0.0297],
        [ 0.1077, -0.1108,  0.0122,  ...,  0.0108, -0.1049, -0.1063],
        ...,
        [-0.0787,  0.1259,  0.0803,  ...,  0.1218,  0.1303, -0.1351],
        [ 0.1359,  0.0175, -0.0673,  ...,  0.0674,  0.0676,  0.1058],
        [ 0.0790,  0.1343, -0.0293,  ...,  0.0344, -0.0971, -0.0509]],
       requires_grad=True)

In [11]:
torch.manual_seed(123)
model = NeuralNetwork(50, 3)
model.layers[0].weight

Parameter containing:
tensor([[-0.0577,  0.0047, -0.0702,  ...,  0.0222,  0.1260,  0.0865],
        [ 0.0502,  0.0307,  0.0333,  ...,  0.0951,  0.1134, -0.0297],
        [ 0.1077, -0.1108,  0.0122,  ...,  0.0108, -0.1049, -0.1063],
        ...,
        [-0.0787,  0.1259,  0.0803,  ...,  0.1218,  0.1303, -0.1351],
        [ 0.1359,  0.0175, -0.0673,  ...,  0.0674,  0.0676,  0.1058],
        [ 0.0790,  0.1343, -0.0293,  ...,  0.0344, -0.0971, -0.0509]],
       requires_grad=True)

In [12]:
torch.manual_seed(123)
X = torch.rand((1, 50))
out = model(X)
out

tensor([[-0.1262,  0.1080, -0.1792]], grad_fn=<AddmmBackward0>)

In [13]:
with torch.no_grad():
    out = model(X)
out

tensor([[-0.1262,  0.1080, -0.1792]])

In [14]:
with torch.no_grad():
    out = torch.softmax(model(X), dim=1)
out

tensor([[0.3113, 0.3934, 0.2952]])

In [15]:
torch.sum(out)

tensor(1.)

In [16]:
X_train = torch.tensor([
    [-1.2, 3.1],
    [-0.9, 2.9],
    [-0.5, 2.6],
    [2.3, -1.1],
    [2.7, -1.5]
])
y_train = torch.tensor([0, 0, 0, 1, 1])

X_test = torch.tensor([
    [-0.8, 2.8],
    [2.6, -1.6]
])
y_test = torch.tensor([0, 1])

In [17]:
from torch.utils.data import Dataset

class ToyDataset(Dataset):
    def __init__(self, X, y):
        self.features = X
        self.labels = y

    def __getitem__(self, index):
        one_x = self.features[index]
        one_y = self.labels[index]
        return one_x, one_y

    def __len__(self):
        return self.labels.shape[0]

train_ds = ToyDataset(X_train, y_train)
test_ds = ToyDataset(X_test, y_test)

In [20]:
from torch.utils.data import DataLoader

torch.manual_seed(123)

train_loader = DataLoader(
    dataset=train_ds,
    batch_size=2,
    shuffle=True,
    num_workers=0,
    drop_last=True
)

test_loader = DataLoader(
    dataset=test_ds,
    batch_size=2,
    shuffle=False,
    num_workers=0
)

In [21]:
for idx, (X, y) in enumerate(train_loader):
    print(f"Batch: {idx + 1}", X, y)

Batch: 1 tensor([[ 2.3000, -1.1000],
        [-0.9000,  2.9000]]) tensor([1, 0])
Batch: 2 tensor([[-1.2000,  3.1000],
        [-0.5000,  2.6000]]) tensor([0, 0])


In [26]:
import torch.nn.functional as F

torch.manual_seed(123)
model = NeuralNetwork(2, 2)
optimizer = torch.optim.SGD(
    model.parameters(), lr=0.5
)

num_epochs = 3
for epoch in range(num_epochs):
    model.train()
    for batch_idx, (features, labels) in enumerate(train_loader):
        logits = model(features)
        loss = F.cross_entropy(logits, labels)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        print(f"Epoch: {epoch + 1:03d}/{num_epochs} | Loss {loss}")
    model.eval()

Epoch: 001/3 | Loss 0.7487356662750244
Epoch: 001/3 | Loss 0.6450306177139282
Epoch: 002/3 | Loss 0.44225579500198364
Epoch: 002/3 | Loss 0.12562280893325806
Epoch: 003/3 | Loss 0.026905544102191925
Epoch: 003/3 | Loss 0.0043272399343550205


In [27]:
sum(param.numel() for param in model.parameters() if param.requires_grad)

752

In [28]:
model.eval()
with torch.no_grad():
    outputs = model(X_train)
outputs

tensor([[ 2.8569, -4.1618],
        [ 2.5382, -3.7548],
        [ 2.0944, -3.1820],
        [-1.4814,  1.4816],
        [-1.7176,  1.7342]])

In [30]:
torch.set_printoptions(sci_mode=False)
probas = torch.softmax(outputs, dim=1)
print(probas)

tensor([[    0.9991,     0.0009],
        [    0.9982,     0.0018],
        [    0.9949,     0.0051],
        [    0.0491,     0.9509],
        [    0.0307,     0.9693]])


In [31]:
preds = torch.argmax(probas, dim=1)
preds

tensor([0, 0, 0, 1, 1])

In [36]:
def compute_accuracy(model, dataloader):
    model = model.eval()
    correct = 0
    total_examples = 0
    for idx, (features, labels) in enumerate(dataloader):
        with torch.no_grad():
            logits = model(features)

        preds = torch.argmax(logits, dim=1)
        compare = labels == preds
        correct += torch.sum(compare)
        total_examples += len(compare)
    return (correct / total_examples).item()

In [37]:
compute_accuracy(model, train_loader)

1.0

In [38]:
compute_accuracy(model, test_loader)

1.0

In [39]:
torch.save(model.state_dict(), "model.pth")

In [41]:
model = NeuralNetwork(2, 2)
model.load_state_dict(torch.load("model.pth"))

<All keys matched successfully>

In [42]:
model

NeuralNetwork(
  (layers): Sequential(
    (0): Linear(in_features=2, out_features=30, bias=True)
    (1): ReLU()
    (2): Linear(in_features=30, out_features=20, bias=True)
    (3): ReLU()
    (4): Linear(in_features=20, out_features=2, bias=True)
  )
)

In [44]:
torch.mps.device_count()

1

In [45]:
torch.cpu.device_count()

1

In [49]:
torch.manual_seed(123)
model = NeuralNetwork(2, 2)
device = torch.device("mps")
model = model.to(device)

optimizer = torch.optim.SGD(model.parameters(), lr=0.5)
num_epochs = 3
for epoch in range(num_epochs):
    model.train()
    for idx, (features, labels) in enumerate(train_loader):
        features, labels = features.to(device), labels.to(device)
        logits = model(features)
        loss = F.cross_entropy(logits, labels)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        print(f"epoch: {epoch} | batch: {idx} | loss: {loss}")
    model.eval()

epoch: 0 | batch: 0 | loss: 0.7487356662750244
epoch: 0 | batch: 1 | loss: 0.6450306177139282
epoch: 1 | batch: 0 | loss: 0.44225579500198364
epoch: 1 | batch: 1 | loss: 0.12562280893325806
epoch: 2 | batch: 0 | loss: 0.026905544102191925
epoch: 2 | batch: 1 | loss: 0.0043272399343550205


model

In [52]:
features

tensor([[-0.9000,  2.9000],
        [-0.5000,  2.6000]], device='mps:0')

In [54]:
features.to("mps")

tensor([[-0.9000,  2.9000],
        [-0.5000,  2.6000]], device='mps:0')

In [55]:
a = torch.rand(10, 10)

In [56]:
a

tensor([[0.4007, 0.9541, 0.8567, 0.4604, 0.2238, 0.3047, 0.3019, 0.7772, 0.4963,
         0.3846],
        [0.0948, 0.5410, 0.8090, 0.8157, 0.5431, 0.9595, 0.3764, 0.8885, 0.7794,
         0.9417],
        [0.7576, 0.0499, 0.7448, 0.1388, 0.1651, 0.1491, 0.2685, 0.0509, 0.9271,
         0.2894],
        [0.8272, 0.9483, 0.8171, 0.8718, 0.5126, 0.0086, 0.8053, 0.0787, 0.6293,
         0.2914],
        [0.8203, 0.8336, 0.4739, 0.3258, 0.8870, 0.3426, 0.1150, 0.1767, 0.0215,
         0.8699],
        [0.8756, 0.3727, 0.7206, 0.7847, 0.2988, 0.5849, 0.4149, 0.2594, 0.1849,
         0.2540],
        [0.4626, 0.4399, 0.1210, 0.0457, 0.4320, 0.6941, 0.6661, 0.1499, 0.7697,
         0.1543],
        [0.2570, 0.9078, 0.6252, 0.6827, 0.0185, 0.0652, 0.4068, 0.9610, 0.0068,
         0.7761],
        [0.2644, 0.1429, 0.8873, 0.1202, 0.6813, 0.3728, 0.8571, 0.0257, 0.7619,
         0.8098],
        [0.6170, 0.9368, 0.9163, 0.7747, 0.8472, 0.9266, 0.8811, 0.7464, 0.1591,
         0.7705]])

In [57]:
%timeit a@a

636 ns ± 15.5 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [58]:
%timeit a.to("mps")@a.to("mps")

237 μs ± 1.13 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [67]:
a = torch.rand(10000, 10000)

In [74]:
%timeit -n 10 a@a

678 ms ± 1.35 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [79]:
%timeit -n 10 b@b

The slowest run took 2721.15 times longer than the fastest. This could mean that an intermediate result is being cached.
39.3 ms ± 95.8 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [78]:
b = a.to("mps")

In [80]:
b = a.to("cpu")